# ----
# Site

title: dev-library
url: "https://doorisopen.github.io/developers-library"
baseurl:
google_analytics_key: "UA-165000136-2"
show_full_navigation: true

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: dev-library
author: doorisopen
name: doorisopen
email: 
twitter: # twitter username without the @ symbol
social:
name: Edition Template
links:

# Conversion
markdown: kramdown
highlighter: rouge

# Build
encoding: utf-8
permalink: pretty

# image url settings
algorithm_img: developers-library/images/algorithm
datastructure_img: developers-library/images/datastructure
spring_img: developers-library/images/Spring


plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release


types:
  - minor
  - major

# Themplate https://github.com/CloudCannon/edition-jekyll-template